term / year drop-down menu
ConnorBrhely/ScrumMasters361 pull request #19
Opened 2023-05-10 14:09 UTC by SleepingLink1

consolidated drop down menu into single form drop-down. Modified views to accept single string, parse it, and assign term / year to course.

2023-05-10 23:36 UTC, ConnorBrhely approved these changes

2023-05-10 23:36 UTC, Apollogeist reviewed
Looks good!

2023-05-11 01:49 UTC, Apollogeist requested changes

2023-05-11 01:49 UTC, Apollogeist commented on TAScheduler/templates/home.html
Uncomment the account_info template, otherwise good.

2023-05-14 20:09 UTC, SleepingLink1 commented
uncommented the accounts template. Added some bootstrap to the view courses and made empty files for the views. Will continue working on them and commit more soon.

2023-05-14 20:10 UTC, merged